### ISSUE TITLE
Publish artifact to sonatype

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/tinkergraph-gremlin#1]
This is our custom version of the tinkergraph. It fixes a critical bug in indexing that's not fixed upstream, and it will be the place where @mpollmeier places our tuned TinkerGraph that will reduce memory usage significantly. Once this is published, this can be merged:
https://github.com/ShiftLeftSecurity/cpg2sp/pull/138

**Comment by mpollmeier** [comment]
@davyhua I went through all the steps to automatically release the artifact to maven central via sonatype with my fork and that works fine:
* https://github.com/mpollmeier/tinkergraph-gremlin
* https://travis-ci.org/mpollmeier/tinkergraph-gremlin
* https://oss.sonatype.org/content/repositories/public/com/michaelpollmeier/tinkergraph-gremlin/
* https://repo1.maven.org/maven2/com/michaelpollmeier/tinkergraph-gremlin/

We want to deploy this artifact under the Shiftleft banner though, and for that I need you to do the following:
1) sign up for a sonatype account: http://central.sonatype.org/pages/ossrh-guide.html
2) create a gpg keypair for signing: http://www.debonair.io/post/maven-cd/
2a) encrypt the private key for travis (`travis encrypt-file privkey.asc`) and store in `travis` directory of the repo
3) encrypt the sonatype password and the private key passphrase for travis.ci, using their command line tool https://github.com/travis-ci/travis.rb#encrypt
```
cd tinkergraph-gremlin
travis encrypt SONATYPE_PASS=abc
travis encrypt GPG_PASS=def
```
4) change the env.global entries in .travis.yml to use values (GPG_KEY_NAME, SONATYPE_USER, secure, secure)

I just went through all of the above, so just get in touch if you're stuck anywhere or have some questions. 
I'm happy to do that as well, but since you usually hold the master keys, it's probably best if we continue that way.

**Comment by davyhua** [comment]
First step done:  https://issues.sonatype.org/browse/OSSRH-36482

**Comment by mpollmeier** [comment]
resolved on their end :)
n.b. you linked my fork (https://github.com/ShiftLeftSecurity/tinkergraph-gremlin), that should have been https://github.com/ShiftLeftSecurity/tinkergraph-gremlin, but that shouldn't matter. All that counts is that we can publish to `io.shiftleft`, which we'll test once steps 2-4 are done.

**Comment by davyhua** [comment]
Do I need these steps?

```
The string in place of $keyid is your key id.
Submit your key to the ubuntu server with
$ gpg --send-keys --keyserver keyserver.ubuntu.com $keyid
Submit your key to the MIT server with
$ gpg --send-keys --keyserver pgp.mit.edu $keyid
And once more just to be sure
$ gpg --send-keys --keyserver pool.sks-keyservers.net $keyid
```

**Comment by davyhua** [comment]
Also:

```
$ travis encrypt-file codesigning.asc
Detected repository as ShiftLeftSecurity/tinkergraph-gremlin, is this correct? |yes| 
encrypting codesigning.asc for ShiftLeftSecurity/tinkergraph-gremlin
storing result as codesigning.asc.enc
storing secure env variables for decryption
not logged in - try running travis login --org
davy at jarvis in ~/shiftleft/repo/tinkergraph-gremlin on master*
$ travis login --org
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

davyhua has not granted Travis CI the required permissions, please log in via travis-ci.org
```

What am I missing?

**Comment by mpollmeier** [comment]
the `gpg --send-keys --keyserver ...` is needed to make your public key public, I don't know if it's verified by sonatype and/or maven central, but I would just do it. 

I'm not sure what went wrong with the `travis login --org`. When I did this it asked me to run just `travis login` (without --org), maybe that's the difference? Full docs here: https://github.com/travis-ci/travis.rb#login

**Comment by davyhua** [comment]
I believe everything is ready and good to go.  Please verify here then merge:
https://github.com/ShiftLeftSecurity/tinkergraph-gremlin/tree/davyhua/sonatype

**Comment by mpollmeier** [comment]
updated and merged to master, let's see what travis says :)

**Comment by davyhua** [comment]
Done.  Please try verify again:

https://github.com/ShiftLeftSecurity/tinkergraph-gremlin/tree/davyhua/sonatype

**Comment by mpollmeier** [comment]
Thanks, I adapted the changes in your branch to master.
Deploying a snapshot worked: https://travis-ci.org/ShiftLeftSecurity/tinkergraph-gremlin/builds/316654875
Will close this as soon as I successfully released one version and it made it's way to maven central.

**Comment by mpollmeier** [comment]
release failed because the public key can't be found on any public keyserver... did you upload them?

```
$ gpg --send-keys --keyserver keyserver.ubuntu.com $keyid
Submit your key to the MIT server with
$ gpg --send-keys --keyserver pgp.mit.edu $keyid
And once more just to be sure
$ gpg --send-keys --keyserver pool.sks-keyservers.net $keyid
```

https://travis-ci.org/ShiftLeftSecurity/tinkergraph-gremlin/builds/316699586?utm_source=email&utm_medium=notification

```
[ERROR] Repository "ioshiftleft-1000" failures

[ERROR]   Rule "signature-staging" failures

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://pgp.mit.edu:11371/&gt;http://pgp.mit.edu:11371/&lt;/a&gt;. Upload your public key and try the operation again.

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://keyserver.ubuntu.com:11371/&gt;http://keyserver.ubuntu.com:11371/&lt;/a&gt;. Upload your public key and try the operation again.

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://pool.sks-keyservers.net:11371/&gt;http://pool.sks-keyservers.net:11371/&lt;/a&gt;. Upload your public key and try the operation again.

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://pgp.mit.edu:11371/&gt;http://pgp.mit.edu:11371/&lt;/a&gt;. Upload your public key and try the operation again.

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://keyserver.ubuntu.com:11371/&gt;http://keyserver.ubuntu.com:11371/&lt;/a&gt;. Upload your public key and try the operation again.

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://pool.sks-keyservers.net:11371/&gt;http://pool.sks-keyservers.net:11371/&lt;/a&gt;. Upload your public key and try the operation again.

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://pgp.mit.edu:11371/&gt;http://pgp.mit.edu:11371/&lt;/a&gt;. Upload your public key and try the operation again.

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://keyserver.ubuntu.com:11371/&gt;http://keyserver.ubuntu.com:11371/&lt;/a&gt;. Upload your public key and try the operation again.

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://pool.sks-keyservers.net:11371/&gt;http://pool.sks-keyservers.net:11371/&lt;/a&gt;. Upload your public key and try the operation again.

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://pgp.mit.edu:11371/&gt;http://pgp.mit.edu:11371/&lt;/a&gt;. Upload your public key and try the operation again.

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://keyserver.ubuntu.com:11371/&gt;http://keyserver.ubuntu.com:11371/&lt;/a&gt;. Upload your public key and try the operation again.

[ERROR]     * No public key: Key with id: (b6c58b8082504ccf) was not able to be located on &lt;a href=http://pool.sks-keyservers.net:11371/&gt;http://pool.sks-keyservers.net:11371/&lt;/a&gt;. Upload your public key and try the operation again.
```

**Comment by davyhua** [comment]
```
pub   rsa4096 2017-12-12 [SC]
      3879C93F1E7165928F2CA8BBA87EF1FF9E91C595
uid           [ultimate] ShiftLeft <services@shiftleft.io>
sub   rsa4096 2017-12-12 [E]
sub   rsa4096 2017-12-12 [S] [expires: 2037-12-07]

$ gpg --send-keys --keyserver keyserver.ubuntu.com 3879C93F1E7165928F2CA8BBA87EF1FF9E91C595
gpg: sending key A87EF1FF9E91C595 to hkp://keyserver.ubuntu.com
$ gpg --send-keys --keyserver pgp.mit.edu 3879C93F1E7165928F2CA8BBA87EF1FF9E91C595
gpg: sending key A87EF1FF9E91C595 to hkp://pgp.mit.edu
$ gpg --send-keys --keyserver pool.sks-keyservers.net 3879C93F1E7165928F2CA8BBA87EF1FF9E91C595
gpg: sending key A87EF1FF9E91C595 to hkp://pool.sks-keyservers.net
```

**Comment by mpollmeier** [comment]
yay, that worked, artifacts are on sonatype: https://oss.sonatype.org/content/repositories/public/io/shiftleft/tinkergraph-gremlin/3.3.0.0/

final step: they *should* automatically get synched to maven central within a few hours

**Comment by mpollmeier** [comment]
yay: https://repo1.maven.org/maven2/io/shiftleft/tinkergraph-gremlin/3.3.0.0/

**Comment by davyhua** [comment]
:tada:
